### ISSUE TITLE
Joining a 8x8 room from android results in empty room

### ISSUE THREAD

**Issue by Piet-G** [calvinckho/capacitor-jitsi-meet#103]
This is a regression in the latest version (4.1.0), when we attempt to join a room from android we are placed into a room but the other participant is not visible. The other party also can't see the android user.

Other platforms (Web and Ios) can still join rooms with eachother fine.

We reverted to version 4.0.0 and it worked fine again.

**Comment by calvinckho** [comment]
@Piet-G, a newer version has since been released: 5.0.0, which utilizes the 9.2.0 SDK. can you try it and report the outcome?

Also, Capacitor 6 is out and the 6.0.0 version for this plugin is in beta testing. You can install it using this command and report your outcome as well:

`npm i git+ssh://git@github.com:calvinckho/capacitor-jitsi-meet#capacitor-6`

**Comment by calvinckho** [comment]
@Piet-G I will close it for now. If you have tested it using the new version and it still has issue, we can reopen this.
