### ISSUE TITLE
[Question] Share screen of the app that start the share screen

### ISSUE THREAD

**Issue by manuuarizaa** [calvinckho/capacitor-jitsi-meet#57]
Hi @calvinckho , thanks for your work! I have a question for you, when I start share screen in my app all work perfectly, but I need to share the app where I start the share screen, and I dont have way to do this, how can I do that? Thanks!

**Comment by calvinckho** [comment]
the Jitsi team just added this documentation on screen sharing. though not related to the full screen setting above, it might still be useful: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk#screen-sharing-integration

I will close this for now, since iOS share screen involves adding an app extension and does not work out-of-the-box with this plugin.
