### ISSUE TITLE
Is it possible to use "Commands" on this plugin? The same ones available on web? Would I have to customize the SDK??

### ISSUE THREAD

**Issue by tgprudencio** [calvinckho/capacitor-jitsi-meet#80]
I have Jitsi implemented on web project and now I need to implement using Ionic for Android and iOS, but here's the thing:

the features "screen sharing", "mute everyone", "recording" and "leave meeting" are external buttons, so they are not placed on toolbox, and in order to use them, I have to use the commands form Jitsi Docs... I would like to know if that's possible using this plugin? If so, I assume I would need to customize the SDK and rebuild to use, but since I've never done that (customize and build my own SDK), I don't even know if I could achieve what I want... where could I start from? Thanks.

**Comment by calvinckho** [comment]
Hi @tgprudencio, thank you for your question. Here are the supported commands for the Web implementation, Android SDK, and iOS SDK are:

Web and Mobile SDKs Support:

Web Implementation: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-commands
Android SDK: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#broadcasting-actions
iOS SDK: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk/#jitsimeetview-class

as you can see, "toggling screen sharing" and "hang up/leave meeting" are supported in Web and the mobile SDKs. "Mute everyone" and "recording" are only supported in the Web Implementation and not in the mobile SDKs.

Capacitor Plugin Support:

Only the "hang up" command is supported (i.e. the leaveConference() method). The toggle screen sharing method is not yet supported in our plugin, because screen sharing is not fully functional in the Android SDK. See https://github.com/calvinckho/capacitor-jitsi-meet/issues/35. On iOS, I have not tried to implement it. But theoretically, it can be done using the instructions documented in the Jitsi handbook: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk/#screen-sharing-integration.

**Comment by calvinckho** [comment]
I am open to adding the toggle screen share method in the future when people begin to report their successes with getting it to work on both Android and iOS.

**Comment by tgprudencio** [comment]
Hi @calvinckho, thank you for the reply... For now I intend to let recording and screen sharing features aside then... I can use the plugin successfully for other purposes (and thank you for that)... I've got just one more question:

- I still need to use one Command which is "getParticipantsInfo", and I saw on the link you attached for iOS SDK that there is this one: "retrieveParticipantsInfo"... I assume they are the same, right? And to make it work, would I have to customize the SDK?

**Comment by calvinckho** [comment]
Adding those commands are possible by customizing the plugin. You are welcome to add those code, submit a PR and I can merge the code after testing them.
